[package]
name = "bits_and_bytes"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
strip = "symbols"

[dependencies]
iced = { version = "0.13.1", features = ["image"] }


[build-dependencies]
winres = "0.1"
